package service

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/multica-ai/multica/server/internal/util"
	"github.com/multica-ai/multica/server/pkg/skillbundle"
)

// capAccum collects one capability's materialized content + bindings.
type capAccum struct {
	id          string
	name        string
	description string
	entrypoint  string
	files       []AgentSkillFileData
	bindings    []capBindingInfo
}

// capBindingInfo is the subset of a binding row used to render the binding note.
type capBindingInfo struct {
	profile     string
	requirement string
	required    bool
	mode        string
	fallback    string
}

// LoadBoundSharedCapabilities materializes the shared capabilities bound to an
// agent into AgentSkillData bundles (one per capability) plus a generated
// machine-owned binding-note skill that tells the runtime which role skill uses
// which capability profile and restrictions.
//
// This is the M3 runtime-injection entry point. It is called by
// LoadAgentSkillBundles so both the claim-time refs and the resolve endpoint
// automatically include capabilities. The returned bundles carry
// Source=SourceSharedCapability so the daemon's content-addressed cache keeps
// them single-instance and separate from role-owned skills.
//
// The binding note is synthesized (not stored) because it is derived from the
// current bindings on every task; storing it would create a stale-cache hazard.
func (s *TaskService) LoadBoundSharedCapabilities(ctx context.Context, agentID pgtype.UUID) []AgentSkillData {
	rows, err := s.Queries.ListAgentCapabilityBundlesForAgent(ctx, agentID)
	if err != nil {
		return nil
	}
	byCap := make(map[string]*capAccum)
	order := []string{}
	for _, r := range rows {
		capID := util.UUIDToString(r.CapabilityID)
		accum, exists := byCap[capID]
		if !exists {
			accum = &capAccum{
				id:          "capability:" + r.SourceKey,
				name:        r.Name + " (shared capability)",
				description: r.Description,
			}
			byCap[capID] = accum
			order = append(order, capID)
		}
		// Attach file body.
		if r.FileBody.Valid && r.FilePath.Valid {
			if r.IsEntrypoint.Valid && r.IsEntrypoint.Bool {
				accum.entrypoint = r.FileBody.String
			} else {
				accum.files = append(accum.files, AgentSkillFileData{
					Path:    r.FilePath.String,
					Content: r.FileBody.String,
				})
			}
		}
		// Record the binding for the binding-note generator.
		if r.BindingID.Valid {
			accum.bindings = append(accum.bindings, capBindingInfo{
				profile:      r.Profile,
				requirement:  r.VersionRequirement,
				required:     r.Required,
				mode:         extractMode(r.Permissions),
				fallback:     extractBehavior(r.Fallback),
			})
		}
	}

	out := make([]AgentSkillData, 0, len(order))
	for _, capID := range order {
		accum := byCap[capID]
		// Skip capabilities with no content yet (version not materialized).
		if accum.entrypoint == "" && len(accum.files) == 0 {
			continue
		}
		sort.Slice(accum.files, func(i, j int) bool { return accum.files[i].Path < accum.files[j].Path })
		out = append(out, AgentSkillData{
			ID:          accum.id,
			Source:      skillbundle.SourceSharedCapability,
			Name:        accum.name,
			Description: accum.description,
			Content:     accum.entrypoint,
			Files:       accum.files,
		})
	}

	// Generate the machine-owned binding note.
	if note := buildCapabilityBindingNote(byCap, order); note != "" {
		out = append(out, AgentSkillData{
			ID:          "agentwaker:capability-bindings",
			Source:      skillbundle.SourceSharedCapability,
			Name:        "Capability bindings",
			Description: "Machine-generated: maps role skills to shared-capability profiles and permissions.",
			Content:     note,
		})
	}
	return out
}

// buildCapabilityBindingNote renders the machine-owned binding note as Markdown.
func buildCapabilityBindingNote(byCap map[string]*capAccum, order []string) string {
	var sb stringsBuilder
	hasAny := false
	for _, capID := range order {
		accum := byCap[capID]
		if len(accum.bindings) == 0 {
			continue
		}
		if !hasAny {
			sb.WriteString("# Capability bindings\n\n")
			sb.WriteString("This file is machine-generated by Multica. It maps the shared\n")
			sb.WriteString("capabilities bound to this agent to the profiles and permission\n")
			sb.WriteString("restrictions declared by the source AgentWaker directory. Do not\n")
			sb.WriteString("edit; it is regenerated on every task.\n\n")
			hasAny = true
		}
		sb.WriteString(fmt.Sprintf("## %s\n\n", accum.name))
		for _, bi := range accum.bindings {
			required := "optional"
			if bi.required {
				required = "required"
			}
			sb.WriteString(fmt.Sprintf("- profile: `%s` (%s)\n", bi.profile, required))
			if bi.requirement != "" {
				sb.WriteString(fmt.Sprintf("  - version requirement: `%s`\n", bi.requirement))
			}
			if bi.mode != "" {
				sb.WriteString(fmt.Sprintf("  - permission mode: `%s`\n", bi.mode))
			}
			if bi.fallback != "" {
				sb.WriteString(fmt.Sprintf("  - fallback: `%s`\n", bi.fallback))
			}
		}
		sb.WriteString("\n")
	}
	if !hasAny {
		return ""
	}
	return sb.String()
}

// stringsBuilder is a thin alias for strings.Builder to keep the import list
// minimal in this file.
type stringsBuilder = strings.Builder

func extractMode(perms []byte) string {
	if len(perms) == 0 {
		return ""
	}
	// permissions JSONB shape: {"mode":"read-only"} or {"mode":"...","account_actions":bool}
	var m map[string]any
	if err := json.Unmarshal(perms, &m); err != nil {
		return ""
	}
	if mode, ok := m["mode"].(string); ok {
		return mode
	}
	return ""
}

func extractBehavior(fallback []byte) string {
	if len(fallback) == 0 {
		return ""
	}
	var m map[string]any
	if err := json.Unmarshal(fallback, &m); err != nil {
		return ""
	}
	if behavior, ok := m["behavior"].(string); ok {
		return behavior
	}
	return ""
}
